/**
 * key-page.js — Dynamic page template for each keyboard key.
 *
 * Generated by gatsby-node.js for every KeyboardKey in Contentful.
 * URL pattern:  /key/:keyId   (e.g. /key/C, /key/D%23)
 *
 * The form uses React state so edits are local for now.
 * To persist changes, replace the handleSave stub with a
 * fetch() call to the Contentful Management API.
 */

import React, { useState } from "react"
import { graphql, Link } from "gatsby"
import Layout from "../components/layout"
import Seo from "../components/seo"

// ---------- page component ----------

function KeyPage({ data }) {
  // Pull the Contentful node passed in via GraphQL query below
  const key = data.contentfulKeyboardKey

  // Local state for the editable fields
  const [assignedNote, setAssignedNote] = useState(key.assignedNote ?? "")
  const [octave, setOctave] = useState(key.octave ?? "")
  const [saved, setSaved] = useState(false) // tracks whether the user has "saved"

  function handleSave(e) {
    e.preventDefault()

    /**
     * TODO: persist to Contentful via the Management API.
     *
     * Example (requires your Management Token in .env.development):
     *
     * const client = createClient({ accessToken: process.env.CONTENTFUL_MANAGEMENT_TOKEN })
     * const space  = await client.getSpace(process.env.SPACE_ID)
     * const env    = await space.getEnvironment("master")
     * const entry  = await env.getEntry(key.contentful_id)
     * entry.fields.assignedNote["en-US"] = assignedNote
     * entry.fields.octave["en-US"]       = Number(octave)
     * await entry.update()
     * await entry.publish()
     */

    setSaved(true)
    setTimeout(() => setSaved(false), 3000)
  }

  return (
    <Layout>
      {/* ---- header ---- */}
      <nav style={{ marginBottom: "1rem" }}>
        <Link to="/">← Back to keyboard</Link>
      </nav>

      <h1>Key: {key.keyId}</h1>

      {/* ---- current values ---- */}
      <section style={{ marginBottom: "2rem" }}>
        <h2>Current configuration</h2>
        <table style={{ borderCollapse: "collapse" }}>
          <tbody>
            <tr>
              <Th>Key ID</Th>
              <td style={tdStyle}>{key.keyId}</td>
            </tr>
            <tr>
              <Th>Assigned note</Th>
              <td style={tdStyle}>{key.assignedNote}</td>
            </tr>
            <tr>
              <Th>Octave</Th>
              <td style={tdStyle}>{key.octave ?? "—"}</td>
            </tr>
          </tbody>
        </table>
      </section>

      {/* ---- edit form ---- */}
      <section>
        <h2>Edit configuration</h2>
        <p style={{ color: "#666", fontSize: "0.9rem" }}>
          Changes are local (React state) until you connect the Contentful
          Management API.
        </p>

        <form onSubmit={handleSave} style={{ display: "flex", flexDirection: "column", gap: "1rem", maxWidth: "320px" }}>
          {/* Assigned Note */}
          <label style={labelStyle}>
            Assigned note
            <input
              type="text"
              value={assignedNote}
              onChange={e => { setAssignedNote(e.target.value); setSaved(false) }}
              placeholder="e.g. C4, D#3"
              style={inputStyle}
              required
            />
            <small style={{ color: "#888" }}>
              Standard scientific pitch notation: note name + octave number.
            </small>
          </label>

          {/* Octave */}
          <label style={labelStyle}>
            Octave (optional)
            <input
              type="number"
              value={octave}
              onChange={e => { setOctave(e.target.value); setSaved(false) }}
              placeholder="e.g. 4"
              min={0}
              max={8}
              style={inputStyle}
            />
          </label>

          <button type="submit" style={buttonStyle}>
            Save changes
          </button>

          {saved && (
            <p style={{ color: "green", margin: 0 }}>
              ✓ Saved locally! (Wire up the Contentful API to persist.)
            </p>
          )}
        </form>
      </section>
    </Layout>
  )
}

// ---------- tiny style helpers ----------
const Th = ({ children }) => (
  <th style={{ textAlign: "left", padding: "4px 16px 4px 0", color: "#555", fontWeight: 600 }}>
    {children}
  </th>
)
const tdStyle = { padding: "4px 0" }
const labelStyle = { display: "flex", flexDirection: "column", gap: "4px", fontWeight: 600 }
const inputStyle = {
  padding: "8px 10px",
  border: "1px solid #ccc",
  borderRadius: "4px",
  fontSize: "1rem",
  fontWeight: "normal",
}
const buttonStyle = {
  padding: "10px 20px",
  background: "#7026b9",
  color: "#fff",
  border: "none",
  borderRadius: "4px",
  fontSize: "1rem",
  cursor: "pointer",
}

// ---------- SEO head export ----------
export const Head = ({ data }) => (
  <Seo title={`Key: ${data.contentfulKeyboardKey.keyId}`} />
)

// ---------- GraphQL query ----------
//
// Fetches a single KeyboardKey by its keyId.
// The $keyId variable is injected by gatsby-node.js createPages context.
//
export const query = graphql`
  query KeyPageQuery($keyId: String!) {
    contentfulKeyboardKey(keyId: { eq: $keyId }) {
      keyId
      assignedNote
      octave
      contentful_id
    }
  }
`

export default KeyPage
